type ProjectData = {
    id: number;
    title: string;
    description: string;
    technicalStack: string[];
    link?: string[];
    category: string;
    tags: string[];
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    yearOfDevelopment: string;
    image?: string;
};

const projectData: ProjectData[] = [
    {
        id: 1,
        title: "Task Manager",
        description: "Deployment-ready secure task management application.",
        technicalStack: ['Python', 'Flask', 'Redis', 'Postgres', 'Docker', 'Kubernetes', 'Helm'],
        link: ['https://github.com/imdhruv99/Task-Manager'],
        category: 'Web Development',
        tags: ['Containerization', 'Task Management', 'Docker', 'Kubernetes', 'Scalability'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Apr 2025 - May 2025",
        // image: '/images/task_manager.png',
    },
    {
        id: 2,
        title: "IdeaBeacon",
        description: "Community site for idea posting and brainstorming.",
        technicalStack: ['NodeJs', 'ExpressJs', 'ReactJS', 'Docker', 'MongoDB'],
        link: ['https://github.com/imdhruv99/IdeaBeacon-FrontEnd/', 'https://github.com/imdhruv99/IdeaBeacon-BackEnd'],
        category: 'Full Stack Development',
        tags: ['NodeJs', 'ExpressJs', 'ReactJS', 'Docker', 'MongoDB'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Jul 2024 - Sept 2024",
        // image: '/images/idea_beacon.png',
    },
    {
        id: 3,
        title: "Face Mask Detection",
        description: "Real-time face mask detection using deep learning.",
        technicalStack: ['Python', 'Keras', 'CV2'],
        link: ['https://github.com/imdhruv99/FaceMask-Detection'],
        category: 'Machine Learning',
        tags: ['Computer Vision', 'Deep Learning', 'Real-time', 'Mask Detection', 'AI'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "May 2021 - Jun 2021",
    },
    {
        id: 4,
        title: "Employee Retention",
        description: "ML web app for predicting employee retention.",
        technicalStack: ['Python', 'Flask', 'Sklearn', 'Docker', 'ELK Stack'],
        link: ['https://github.com/imdhruv99/Employee-Retention-Prediction'],
        category: 'Machine Learning',
        tags: ['Employee Retention', 'ML', 'Flask', 'XGBoost', 'Data Visualization', 'Docker'],
        difficulty: 'Advanced',
        yearOfDevelopment: "Apr 2021 - Jul 2021",
    },
    {
        id: 5,
        title: "OCR Neural Net",
        description: "Neural network from scratch for basic OCR tasks.",
        technicalStack: ['Python', 'Numpy', 'JavaScript'],
        link: ['https://github.com/imdhruv99/My-Own-Neural-Network'],
        category: 'Machine Learning',
        tags: ['Neural Network', 'OCR', 'Deep Learning', 'Computer Vision'],
        difficulty: 'Advanced',
        yearOfDevelopment: "May 2021 - Jun 2021",
    },
    {
        id: 6,
        title: "Object Detection",
        description: "Django app with ResNet50 for detecting objects.",
        technicalStack: ['Python', 'Django', 'Tensorflow', 'Keras'],
        link: ['https://github.com/imdhruv99/ObjectDetection-Resnet50-Django'],
        category: 'Web Development',
        tags: ['Object Detection', 'Deep Learning', 'Django', 'Computer Vision', 'ResNet50'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Nov 2022 - Dec 2022",
    },
    {
        id: 7,
        title: "DevOps Workflows",
        description: "Automated DevOps setup using Jenkins, Docker, and AWS.",
        technicalStack: ['Go', 'Gin', 'Jenkins', 'Docker', 'Terraform', 'Ansible', 'AWS'],
        link: ['https://github.com/imdhruv99/DevOps-Automation'],
        category: 'DevOps',
        tags: ['CI/CD', 'Automation', 'Jenkins', 'Docker', 'AWS', 'Terraform', 'Ansible'],
        difficulty: 'Advanced',
        yearOfDevelopment: "Jun 2024 - Jul 2024",
    },
    {
        id: 8,
        title: "Forest Fire Prediction",
        description: "Predict forest fires using logistic regression model.",
        technicalStack: ['Python', 'Flask', 'Sklearn', 'JavaScript'],
        link: ['https://github.com/imdhruv99/LogisticRegression-Flask-ForestFirePreventation'],
        category: 'Machine Learning',
        tags: ['Logistic Regression', 'Flask', 'Predictive Modeling', 'Forest Fire Prevention', 'Sklearn'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Jan 2020 - Feb 2020",
    },
    {
        id: 9,
        title: "Blog-OAuth2.0",
        description: "RESTful blog API using Node, Express, OAuth2.",
        technicalStack: ['NodeJs', 'ExpressJs', 'OAuth2', 'MongoDB'],
        link: ['https://github.com/imdhruv99/Blog-OAuth2-Nodejs'],
        category: 'Backend Development',
        tags: ['OAuth2', 'Node.js', 'Express', 'MongoDB', 'Authentication'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Jun 2020 - Jul 2020",
    },
    {
        id: 10,
        title: "Go Chat App",
        description: "Real-time Go chat app using Gorilla WebSocket.",
        technicalStack: ['Go', 'Gorilla WebSocket', 'Docker'],
        link: ['https://github.com/imdhruv99/Golang-Gorilla-WebSocket-ChatApp-Docker'],
        category: 'Backend Development',
        tags: ['Go', 'WebSocket', 'Real-time', 'Chat Application', 'Docker'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Mar 2020 - Apr 2020",
    },
    {
        id: 11,
        title: "DynRestAPI",
        description: "Minimal Node.js setup for dynamic RESTful APIs.",
        technicalStack: ['NodeJs'],
        link: ['https://github.com/imdhruv99/Dynamic-Rest-Api-Nodejs-Example'],
        category: 'Backend Development',
        tags: ['Node.js', 'REST API', 'Dynamic API', 'Backend'],
        difficulty: 'Intermediate',
        yearOfDevelopment: "Jan 2020 - Feb 2020",
    },
    {
        id: 12,
        title: "Maruti Website",
        description: "PHP-based business website for Maruti import-export.",
        technicalStack: ['PHP', 'JavaScript'],
        link: ['https://github.com/imdhruv99/Maruti-Import-Export'],
        category: 'Web Development',
        tags: ['PHP', 'Dynamic Website', 'Business', 'Frontend', 'Backend'],
        difficulty: 'Beginner',
        yearOfDevelopment: "Feb 2021 - Mar 2021",
    },
    {
        id: 13,
        title: "SkilTal",
        description: "Responsive site for local teaching business.",
        technicalStack: ['HTML', 'CSS', 'JavaScript'],
        link: ['https://github.com/imdhruv99/SkilTal-Website'],
        category: 'Web Development',
        tags: ['Responsive Design', 'HTML', 'CSS', 'JavaScript', 'Website'],
        difficulty: 'Beginner',
        yearOfDevelopment: "Sept 2021 - Oct 2021",
    },
];

export type { ProjectData };
export default projectData;
