const techIconMap: Record<string, { light: string; dark: string }> = {
    Ansible: { light: 'logos:ansible', dark: 'logos:ansible' },
    AWS: { light: 'skill-icons:aws-dark', dark: 'skill-icons:aws-light' },
    CSS: { light: 'logos:css-3', dark: 'logos:css-3' },
    CV2: { light: 'simple-icons:opencv', dark: 'simple-icons:opencv' },
    Django: { light: 'skill-icons:django', dark: 'simple-icons:django' },
    Docker: { light: 'logos:docker-icon', dark: 'logos:docker-icon' },
    ELKStack: { light: 'simple-icons:elasticstack', dark: 'simple-icons:elasticstack' },
    ExpressJs: { light: 'simple-icons:express', dark: 'simple-icons:express' },
    Flask: { light: 'logos:flask', dark: 'bxl:flask' },
    Gin: { light: 'simple-icons:gin', dark: 'simple-icons:gin' },
    Github: { light: 'mdi:github', dark: 'mdi:github' },
    Go: { light: 'logos:go', dark: 'logos:go' },
    Helm: { light: 'logos:helm', dark: 'catppuccin:helm' },
    HTML: { light: 'logos:html-5', dark: 'logos:html-5' },
    JavaScript: { light: 'logos:javascript', dark: 'logos:javascript' },
    Jenkins: { light: 'logos:jenkins', dark: 'logos:jenkins' },
    JupyterNotebook: { light: 'logos:jupyter', dark: 'logos:jupyter' },
    Keras: { light: 'devicon:keras', dark: 'devicon:keras' },
    Kubernetes: { light: 'logos:kubernetes', dark: 'logos:kubernetes' },
    Matplotlib: { light: 'devicon:matplotlib', dark: 'devicon:matplotlib' },
    MongoDB: { light: 'logos:mongodb-icon', dark: 'logos:mongodb-icon' },
    NodeJs: { light: 'logos:nodejs-icon', dark: 'logos:nodejs-icon' },
    Numpy: { light: 'logos:numpy', dark: 'logos:numpy' },
    OAuth2: { light: 'devicon-plain:oauth', dark: 'devicon-plain:oauth' },
    Pandas: { light: 'logos:pandas', dark: 'devicon-plain:pandas-wordmark' },
    PHP: { light: 'skill-icons:php-dark', dark: 'skill-icons:php-light' },
    Postgres: { light: 'logos:postgresql', dark: 'logos:postgresql' },
    Python: { light: 'logos:python', dark: 'logos:python' },
    Redis: { light: 'logos:redis', dark: 'logos:redis' },
    Sklearn: { light: 'skill-icons:scikitlearn-dark', dark: 'skill-icons:scikitlearn-light' },
    Tensorflow: { light: 'logos:tensorflow', dark: 'logos:tensorflow' },
    Terraform: { light: 'logos:terraform-icon', dark: 'logos:terraform-icon' },
    ReactJs: { light:'skill-icons:react-dark', dark:'skill-icons:react-dark' },
};

export default techIconMap;
