const techIconMap: Record<string, { light: string; dark: string }> = {
    Ansible: { light: 'devicon:ansible-wordmark', dark: 'devicon-plain:ansible-wordmark' },
    AWS: { light: 'skill-icons:aws-dark', dark: 'skill-icons:aws-light' },
    Azure: { light: 'material-icon-theme:azure', dark: 'material-icon-theme:azure' },
    CSS: { light: 'logos:css-3', dark: 'logos:css-3' },
    CV2: { light: 'simple-icons:opencv', dark: 'simple-icons:opencv' },
    Django: { light: 'skill-icons:django', dark: 'simple-icons:django' },
    Docker: { light: 'logos:docker-icon', dark: 'logos:docker-icon' },
    ELKStack: { light: 'simple-icons:elasticstack', dark: 'simple-icons:elasticstack' },
    ExpressJs: { light: 'simple-icons:express', dark: 'simple-icons:express' },
    Flask: { light: 'logos:flask', dark: 'bxl:flask' },
    Gin: { light: 'simple-icons:gin', dark: 'simple-icons:gin' },
    Github: { light: 'mdi:github', dark: 'mdi:github' },
    Go: { light: 'logos:go', dark: 'logos:go' },
    Grafana: { light: 'skill-icons:grafana-dark', dark: 'skill-icons:grafana-light' },
    Helm: { light: 'logos:helm', dark: 'catppuccin:helm' },
    HTML: { light: 'logos:html-5', dark: 'logos:html-5' },
    Java: { light: 'logos:java', dark: 'logos:java' },
    JavaScript: { light: 'logos:javascript', dark: 'logos:javascript' },
    Jenkins: { light: 'skill-icons:jenkins-dark', dark: 'skill-icons:jenkins-light' },
    JupyterNotebook: { light: 'logos:jupyter', dark: 'logos:jupyter' },
    Kafka: { light: 'devicon:apachekafka', dark: 'simple-icons:apachekafka' },
    Keras: { light: 'devicon:keras', dark: 'devicon:keras' },
    Kubernetes: { light: 'logos:kubernetes', dark: 'logos:kubernetes' },
    Lightroom: { light: 'logos:adobe-lightroom', dark: 'logos:adobe-lightroom' },
    Linux: { light: 'skill-icons:linux-dark', dark: 'skill-icons:linux-light' },
    Matplotlib: { light: 'devicon:matplotlib', dark: 'devicon:matplotlib' },
    MongoDB: { light: 'logos:mongodb-icon', dark: 'logos:mongodb-icon' },
    MySQL: { light: 'skill-icons:mysql-dark', dark: 'skill-icons:mysql-light' },
    NodeJs: { light: 'logos:nodejs-icon', dark: 'logos:nodejs-icon' },
    Numpy: { light: 'logos:numpy', dark: 'logos:numpy' },
    OAuth2: { light: 'devicon-plain:oauth', dark: 'devicon-plain:oauth' },
    Pandas: { light: 'logos:pandas', dark: 'devicon-plain:pandas-wordmark' },
    PHP: { light: 'skill-icons:php-dark', dark: 'skill-icons:php-light' },
    Photoshop: { light: 'logos:adobe-photoshop', dark: 'logos:adobe-photoshop' },
    Postgres: { light: 'logos:postgresql', dark: 'logos:postgresql' },
    PowerShell: { light: 'material-icon-theme:powershell', dark: 'material-icon-theme:powershell' },
    Python: { light: 'logos:python', dark: 'logos:python' },
    Prometheus: { light: 'devicon:prometheus', dark: 'devicon:prometheus' },
    ReactJs: { light: 'skill-icons:react-dark', dark: 'skill-icons:react-dark' },
    Redis: { light: 'logos:redis', dark: 'logos:redis' },
    Sklearn: { light: 'skill-icons:scikitlearn-dark', dark: 'skill-icons:scikitlearn-light' },
    Splunk: { light: 'logos:splunk', dark: 'simple-icons:splunk' },
    Tensorflow: { light: 'logos:tensorflow', dark: 'logos:tensorflow' },
    Terraform: { light: 'logos:terraform-icon', dark: 'logos:terraform-icon' },
};

export default techIconMap;
